package PetrovTodor.PepeMedicalKids.enums;

public enum TipoArticolo {
    FARMACI,
    AMBULATORIALE,
    DISCARICA,
    CARTUCCE,
    PULIZIE,
    UFFICIO,
    DISPOSITIVI_MEDICI,
    PROTESI,
    MATERIALI_SANITARI,
    STRUMENTI_CHIRURGICI,
    LABORATORIO,
    DIAGNOSTICA,
    STERILIZZAZIONE,
    EMERGENZA,
    MATERIALE_DIDATTICO,
    ABBIGLIAMENTO_PROFESSIONALE
}